// ═══════════════════════════════════════════════════════
// AI SERVICE — All AI features with graceful demo fallback
// When API keys are missing, returns realistic mock data
// ═══════════════════════════════════════════════════════
require('dotenv').config();

const DEMO_MODE = process.env.DEMO_MODE === 'true' || !process.env.OPENAI_API_KEY;

// ── Demo mock responses ──────────────────────────────
const MOCK_RESPONSES = {
  videoBio: {
    transcript: "Mera naam Ramesh Kumar hai. Main 8 saal se painting aur wall finishing ka kaam karta hoon. Delhi aur Noida mein kaam kiya hai. Mera daily rate 800 rupaye hai. Main abhi available hoon.",
    skills: ["Painting", "Wall Finishing", "Interior Painting"],
    experienceYears: 8,
    city: "Delhi NCR",
    summary: "Experienced painter with 8 years in residential and commercial painting in Delhi NCR region.",
    skillTags: [
      { tag: "Painting", confidence: 0.95 },
      { tag: "Wall Finishing", confidence: 0.88 },
      { tag: "8 years experience", confidence: 0.92 },
      { tag: "Available in Delhi", confidence: 0.85 },
    ],
  },

  voiceResume: {
    name: "Ramesh Kumar",
    skills: ["Masonry", "Tiling", "Plastering", "Brick Work"],
    experienceYears: 8,
    city: "Delhi NCR",
    dailyWageINR: 800,
    languages: ["Hindi", "Bhojpuri", "Basic English"],
    about: "Skilled mason with 8 years of experience in residential construction across Delhi NCR. Specializes in brick work, tiling, and plastering. Known for clean finishes and on-time delivery.",
    workTypes: ["Residential Construction", "Commercial Tiling", "Renovation Work"],
  },

  interviewScore: {
    confidence: 76,
    clarity: 82,
    overall: 79,
    feedback: "You spoke clearly about your masonry experience and gave good examples. Your responses were direct and specific. Tip: Try to mention specific project sizes or client names to boost credibility.",
  },

  fraudCheck: (profile) => {
    let riskScore = 0;
    const reasons = [];
    if (!profile.facePhoto && !profile.faceDescriptor) { riskScore += 15; reasons.push("No face verification"); }
    if (!profile.phone) { riskScore += 10; reasons.push("Missing phone number"); }
    if (profile.dailyRate && (profile.dailyRate < 100 || profile.dailyRate > 5000)) { riskScore += 10; reasons.push("Unusual daily rate"); }
    const level = riskScore >= 51 ? 'high' : riskScore >= 21 ? 'medium' : 'low';
    return { riskScore, level, reasons };
  },

  contractText: (data) => `
# WORK AGREEMENT CONTRACT / कार्य अनुबंध

---

## हिंदी / Hindi Section

**कार्य अनुबंध**

यह अनुबंध ${data.clientName} (नियोक्ता) और ${data.workerName} (कर्मचारी) के बीच ${data.startDate} से प्रभावी है।

**कार्य विवरण:** ${data.jobTitle} — ${data.jobDescription}

**स्थान:** ${data.location}

**अवधि:** ${data.duration} दिन

**दैनिक मज़दूरी:** ₹${data.dailyWage}

**कुल राशि:** ₹${data.totalAmount}

**कार्य समय:** ${data.workingHours}

**भुगतान शर्तें:** कार्य पूर्ण होने के 24 घंटे के भीतर UPI/नकद द्वारा भुगतान किया जाएगा।

**समाप्ति खंड:** किसी भी पक्ष को 24 घंटे का नोटिस देना होगा।

**सुरक्षा जिम्मेदारियाँ:** नियोक्ता सुरक्षित कार्य वातावरण प्रदान करेगा। कर्मचारी सुरक्षा नियमों का पालन करेगा।

---

## English Section

**WORK AGREEMENT**

This agreement is between ${data.clientName} (Employer) and ${data.workerName} (Worker), effective ${data.startDate}.

**Job:** ${data.jobTitle} — ${data.jobDescription}

**Location:** ${data.location}

**Duration:** ${data.duration} days

**Daily Wage:** ₹${data.dailyWage}

**Total Amount:** ₹${data.totalAmount}

**Working Hours:** ${data.workingHours}

**Payment Terms:** Payment within 24 hours of work completion via UPI or cash.

**Termination:** Either party may terminate with 24 hours written notice.

**Safety:** Employer provides safe working environment. Worker follows all safety protocols.

**Scope of Work:** ${data.jobDescription}

---

*Digitally generated by AI Digital Workers Platform*
*Generated on: ${new Date().toLocaleDateString('en-IN')}*
`,

  chatbot: (message, role, name) => {
    const lower = message.toLowerCase();
    if (lower.includes('job') || lower.includes('kaam') || lower.includes('نوکری')) {
      return `Namaste ${name}! 👋 ${role === 'worker' ? 'Jobs dhundne ke liye "Find Jobs" section mein jaiye. Apna skill aur location set karein toh AI best matches dikhayega.' : 'New job post karne ke liye "Post Job" button click karein. Aapko title, location, daily wage aur required skills fill karne honge.'}`;
    }
    if (lower.includes('payment') || lower.includes('pay') || lower.includes('paise')) {
      return `Payments ke baare mein: Kaam complete hone ke baad client approve karta hai, phir payment UPI ya cash se hoti hai. Platform 2% fee leta hai. Typical wages Delhi mein ₹600-₹1200/day hain skill ke hisab se.`;
    }
    if (lower.includes('contract') || lower.includes('agreement')) {
      return `AI Contract Maker se professional bilingual contract generate kar sakte hain — Hindi aur English mein. Job accept karne ke baad "Generate Contract" button click karein. PDF download bhi hoga.`;
    }
    if (lower.includes('attendance') || lower.includes('haziri')) {
      return `Attendance face recognition se hoti hai — camera ke saamne aao, system automatically verify kar leta hai. Location GPS se bhi check hoti hai ki aap job site pe ho.`;
    }
    if (lower.includes('profile') || lower.includes('trust') || lower.includes('score')) {
      return `Apna AI Trust Score badhane ke liye: 1) Face verification complete karein 2) Video Bio record karein 3) Interview Score complete karein 4) Real phone number add karein. Higher trust score = more job offers!`;
    }
    if (lower.includes('hello') || lower.includes('hi') || lower.includes('namaste')) {
      return `Namaste ${name}! 🙏 Main AI Digital Workers ka assistant hoon. Aap mujhse puch sakte hain:\n• Jobs kaise dhundein\n• Payment process\n• Contract kaise banayein\n• Profile kaise improve karein\n\nKya madad chahiye?`;
    }
    return `Main samajh gaya. "${message}" ke baare mein: AI Digital Workers platform par ${role === 'worker' ? 'kaam dhundne' : 'workers hire karne'} ke liye help chahiye toh "Support" section check karein ya is chatbot mein specific question poochein. Main Hindi aur English dono mein help kar sakta hoon! 😊`;
  },
};

// ── Real AI functions (with fallback) ─────────────────

async function transcribeAudio(audioBuffer, language = 'hi') {
  if (DEMO_MODE || !process.env.OPENAI_API_KEY) {
    await delay(1500);
    return language === 'hi'
      ? "Mera naam Ramesh Kumar hai. Main 8 saal se kaam karta hoon. Delhi mein rehta hoon. Painting aur wall finishing mera kaam hai."
      : "My name is Ramesh Kumar. I have been working for 8 years. I live in Delhi. Painting and wall finishing is my work.";
  }
  try {
    const { OpenAI } = require('openai');
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const file = new File([audioBuffer], 'audio.webm', { type: 'audio/webm' });
    const resp = await openai.audio.transcriptions.create({ file, model: 'whisper-1', language });
    return resp.text;
  } catch (e) {
    console.error('Whisper error:', e.message);
    return "Audio transcription unavailable in demo mode.";
  }
}

async function extractSkillsFromTranscript(transcript) {
  if (DEMO_MODE || !process.env.OPENAI_API_KEY) {
    await delay(1000);
    return MOCK_RESPONSES.videoBio;
  }
  try {
    const { OpenAI } = require('openai');
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const resp = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [{
        role: 'user',
        content: `Extract skills, experience years, and location from this worker introduction. Return JSON only: { "skills": [], "experienceYears": 0, "city": "", "summary": "", "skillTags": [{"tag":"","confidence":0}] }\n\nTranscript: "${transcript}"`,
      }],
      response_format: { type: 'json_object' },
    });
    return JSON.parse(resp.choices[0].message.content);
  } catch (e) {
    console.error('GPT error:', e.message);
    return MOCK_RESPONSES.videoBio;
  }
}

async function generateVoiceResume(transcript) {
  if (DEMO_MODE || !process.env.ANTHROPIC_API_KEY) {
    await delay(1200);
    return MOCK_RESPONSES.voiceResume;
  }
  try {
    const Anthropic = require('@anthropic-ai/sdk');
    const client    = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });
    const msg = await client.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 1024,
      messages: [{
        role: 'user',
        content: `You are helping create a worker profile for an Indian daily wage worker.\nTranscript: "${transcript}"\nReturn JSON only: {"name":"","skills":[],"experienceYears":0,"city":"","dailyWageINR":0,"languages":[],"about":"","workTypes":[]}`,
      }],
    });
    const text = msg.content[0].text;
    return JSON.parse(text.replace(/```json|```/g, '').trim());
  } catch (e) {
    console.error('Claude error:', e.message);
    return MOCK_RESPONSES.voiceResume;
  }
}

async function scoreInterview(transcripts) {
  if (DEMO_MODE || !process.env.ANTHROPIC_API_KEY) {
    await delay(2000);
    const base  = MOCK_RESPONSES.interviewScore;
    const noise = () => Math.floor(Math.random() * 20) - 10;
    return { ...base, confidence: Math.min(99, Math.max(30, base.confidence + noise())), clarity: Math.min(99, Math.max(30, base.clarity + noise())), overall: Math.min(99, Math.max(30, base.overall + noise())) };
  }
  try {
    const Anthropic = require('@anthropic-ai/sdk');
    const client    = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });
    const msg = await client.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 512,
      messages: [{
        role: 'user',
        content: `Evaluate this Indian daily wage worker interview. Q1: "${transcripts[0]}" Q2: "${transcripts[1]}" Q3: "${transcripts[2]}"\nReturn JSON: {"confidence":0-100,"clarity":0-100,"overall":0-100,"feedback":"2-3 sentences"}`,
      }],
    });
    return JSON.parse(msg.content[0].text.replace(/```json|```/g, '').trim());
  } catch (e) {
    return MOCK_RESPONSES.interviewScore;
  }
}

async function generateContract(data) {
  if (DEMO_MODE || !process.env.ANTHROPIC_API_KEY) {
    await delay(1500);
    return MOCK_RESPONSES.contractText(data);
  }
  try {
    const Anthropic = require('@anthropic-ai/sdk');
    const client    = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });
    const msg = await client.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 2048,
      messages: [{
        role: 'user',
        content: `Generate a professional Hindi + English work agreement for Indian daily wage labour.\nWorker: ${data.workerName}\nClient: ${data.clientName}\nJob: ${data.jobTitle} — ${data.jobDescription}\nLocation: ${data.location}\nStart Date: ${data.startDate}\nDuration: ${data.duration} days\nDaily Wage: ₹${data.dailyWage}\nTotal: ₹${data.totalAmount}\nHours: ${data.workingHours}\nInclude: scope of work, payment terms, termination clause, safety responsibilities. Write Hindi section first then English.`,
      }],
    });
    return msg.content[0].text;
  } catch (e) {
    return MOCK_RESPONSES.contractText(data);
  }
}

async function chatbotReply(message, role, name, history = []) {
  if (DEMO_MODE || !process.env.ANTHROPIC_API_KEY) {
    await delay(800);
    return MOCK_RESPONSES.chatbot(message, role, name);
  }
  try {
    const Anthropic = require('@anthropic-ai/sdk');
    const client    = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });
    const msgs = history.map(h => ({ role: h.role, content: h.content }));
    msgs.push({ role: 'user', content: message });
    const msg = await client.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 400,
      system: `You are the AI assistant for "AI Digital Workers", an Indian labour marketplace. Help daily wage workers and clients. Current user: ${name} (${role}). Reply in simple Hinglish or English. Be concise and helpful. Use ₹ for currency.`,
      messages: msgs,
    });
    return msg.content[0].text;
  } catch (e) {
    return MOCK_RESPONSES.chatbot(message, role, name);
  }
}

function runFraudCheck(profile) {
  return MOCK_RESPONSES.fraudCheck(profile);
}

function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

module.exports = {
  transcribeAudio, extractSkillsFromTranscript, generateVoiceResume,
  scoreInterview, generateContract, chatbotReply, runFraudCheck,
  DEMO_MODE,
};
